dependencies:
  dartino_regexp:
    url: github.com/erikcorry/toit-dartino-regexp
    version: ^0.2.0
  dhtxx:
    url: github.com/toitware/toit-dhtxx
    version: ^1.4.0
  dyp_a01:
    url: github.com/davidg238/dyp_a01
    version: ^1.0.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
